"""initial schema

Revision ID: aeccbbace2e6
Revises: none
Create Date: 2026-10-04 09:48:52.550684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'aeccbbace2e6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resetratelimit',
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('expires_at', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    with op.batch_alter_table('resetratelimit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resetratelimit_expires_at'), ['expires_at'], unique=False)

    op.create_table('traveler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=254), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('traveler', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_traveler_email'), ['email'], unique=True)

    op.create_table('activityevent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('traveler_id', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.Column('identifier', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('outcome', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.ForeignKeyConstraint(['traveler_id'], ['traveler.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activityevent', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activityevent_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_activityevent_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_activityevent_traveler_id'), ['traveler_id'], unique=False)

    op.create_table('authsession',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('traveler_id', sa.Integer(), nullable=False),
    sa.Column('refresh_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('expires_at', sa.Integer(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['traveler_id'], ['traveler.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('authsession', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_authsession_traveler_id'), ['traveler_id'], unique=False)

    op.create_table('googleidentity',
    sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('traveler_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['traveler_id'], ['traveler.id'], ),
    sa.PrimaryKeyConstraint('subject')
    )
    with op.batch_alter_table('googleidentity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_googleidentity_traveler_id'), ['traveler_id'], unique=True)

    op.create_table('passwordresettoken',
    sa.Column('token_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('traveler_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.Integer(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['traveler_id'], ['traveler.id'], ),
    sa.PrimaryKeyConstraint('token_hash')
    )
    with op.batch_alter_table('passwordresettoken', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_passwordresettoken_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_passwordresettoken_traveler_id'), ['traveler_id'], unique=False)

    op.create_table('refreshtoken',
    sa.Column('token_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['authsession.id'], ),
    sa.PrimaryKeyConstraint('token_hash')
    )
    with op.batch_alter_table('refreshtoken', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refreshtoken_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """The baseline contains traveler data; restoring a backup is the rollback."""
    raise RuntimeError("The initial schema cannot be downgraded without deleting traveler data.")
